language: python
python:
  - "2.7_with_system_site_packages"
  - "3.3"
  - "3.4"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-scipy libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq libeigen3-dev
install:
    - pip install numpy --quiet
    - pip install scipy
    - pip install milksets
    - make debug
script: nosetests
